### ISSUE TITLE
Release for Jellyfin 10.7.0

### ISSUE THREAD

**Issue by PrplHaz4** [crobibero/Jellyfin.Channels.LazyMan#10]
Now that Jellyfin 10.7.0 is out, a tagged release and updated manifest would be great!

**Comment by crobibero** [comment]
Thanks for the reminder, I forgot as I’ve been running RC

**Comment by PrplHaz4** [comment]
> 
> 
> Thanks for the reminder, I forgot as I’ve been running RC

Thanks for maintaining it! 🥇Jellyfin MVP for sure...

**Comment by crobibero** [comment]
It be alive in repo

**Comment by PrplHaz4** [comment]
> 
> 
> It be alive in repo

The catalog wouldn't load until I had uninstalled the old LM plugin.  Then installed v10, restarted Jellyfin and all is good.
