### ISSUE TITLE
Roku stuck on resolution choice

### ISSUE THREAD

**Issue by Lanageddon** [crobibero/Jellyfin.Channels.LazyMan#12]
I just did a fresh install of jellyfin 10.7 (windows version if that matters) and added the lazyman plugin. Followed the setup and got it working it chrome, but for some reason when I login on my roku I can click lazyman but it  immediately jumps to the screen where you choose what resolution you want. I've tried uninstall the roku app and reinstalling but it always skips the choice for NHL or MLB as well as the date for the games. I cant go back a page or anything, and when I try to play something the app crashes and takes me back to the roku homescreen.

**Comment by crobibero** [comment]
That might be a limitation of the Roku client. I don’t have a Roku so I’m not able to test

**Comment by Lanageddon** [comment]
Thats what I was afraid of. If I figure it out I'll be sure to let you know. Thanks.

**Comment by PrplHaz4** [comment]
> 
> 
> Thats what I was afraid of. If I figure it out I'll be sure to let you know. Thanks.

Might be worth posting an issue in the roku repo:
https://github.com/jellyfin/jellyfin-roku

Bonus points if you can identify any native functionality or another plugin that shows a similar problem - it sounds like channel plugin navigation/routing maybe?

**Comment by crobibero** [comment]
This should be fixed by the latest Roku release, 1.4.7
