### ISSUE TITLE
MLB games not showing up (NHL ones do and work) 

### ISSUE THREAD

**Issue by shaksiwnl** [crobibero/Jellyfin.Channels.LazyMan#13]
Hi Just set this up on unraid via docker. 

Using linuxservers docker image with latest tag. 

I added the extra parameter: `--add-host mf.svc.nhl.com:165.22.201.101 --add-host mlb-ws-mf.media.mlb.com:165.22.201.101 --add-host playback.svcs.mlb.com:165.22.201.101 `

NHL streams are working as intended but MLB streams are showing day folders with nothing inside.

**Comment by crobibero** [comment]
Sorry for the delay- completely forgot about this issue. I just tested and can't reproduce. Can you try again and see if it's working now?

Screenshot from today's games.
![image](https://user-images.githubusercontent.com/24963659/120086859-e341b780-c09f-11eb-8437-cb1b0a964adc.png)
