### ISSUE TITLE
No games showing up

### ISSUE THREAD

**Issue by sanjunana37** [crobibero/Jellyfin.Channels.LazyMan#14]
I have Jellyfin 10.7 (Windows) installed, and LazyMan 10 (from repository). Host file has been modified, but no games are showing in Lazyman via Jellyfin.

The NHL Games app works fine. Any suggestions?

**Comment by crobibero** [comment]
Sorry I don’t have any ideas why it’s not working for you, I was watching a game earlier so the plugin definitely works.
