### ISSUE TITLE
FR: Add favorite teams/default streams for top-level shortcuts

### ISSUE THREAD

**Issue by PrplHaz4** [crobibero/Jellyfin.Channels.LazyMan#15]
Not sure how this works out, but it'd be nice to have quick access to favorite teams/streams for use in the "Next Up" or over DLNA to jump to a current stream for your favorite team.

In the background I'm thinking you could store and match on sport ("NHL"), team name, stream name (*Home*), stream quality (*720p60*)...

Places this would be useful:
- Next Up
- Favorites
- LazyMan Channel top level results
- "Today's Games"

**Comment by crobibero** [comment]
I won’t be implementing this, but PRs are welcome.
