### ISSUE TITLE
 Plugin Doesn't Open, Tried 10.6 (9.0) and 10.7 (10.0) installs.

### ISSUE THREAD

**Issue by neauxm** [crobibero/Jellyfin.Channels.LazyMan#17]
https://pastebin.com/kM8DXWDi

Windows 10.

Any idea what could be the issue? Clicking plugin from web client or any client only shows 1 spinning circle for a second then black screen.

**Comment by crobibero** [comment]
Sorry, I don't know what could be causing this. My only guess is that there's an error in the browser console.

**Comment by neauxm** [comment]
Any idea how I should fix this? Thank you!
