### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by KX1988** [crobibero/Jellyfin.Channels.LazyMan#22]
Thank you for all your hard work on this.

I see you have updated the repo and plugin, i have updated to the new details but it is still only giving me the option of v9 or v10. 

V11 is not listed.

I reinstalled v10 but I am not able to see anything in the app. Are you seeing the games schedule etc when you go into the plugin?

Thanks again. amazing job for keeping this going whilst Lazyman has stopped in windows.

**Comment by crobibero** [comment]
This is likely because the domain name changed recently. The latest version of the plugin (build for Jellyfin 10.8) should have this fixed now

**Comment by MaDTaZ** [comment]
I cannot see V11.0 to be able to update from v10.0.  Did you build this off of 10.8 Jellyfin which is still listed unstable?

**Comment by crobibero** [comment]
v11 is for 10.8.
Jellyfin 10.8 is alpha, not unstable.

**Comment by MaDTaZ** [comment]
> v11 is for 10.8.
> Jellyfin 10.8 is alpha, not unstable.

I use  linuxserver/jellyfin can I upgrade it to that version?

**Comment by crobibero** [comment]
Linuxserver historically doesn’t support non “stable” releases, so no.

If I have some time in the coming days I may create a 10.1 for Jellyfin 10.7.7

**Comment by MaDTaZ** [comment]
K thanks I tried to switch to jellyfin/jellyfin and the realized the file structure is different

**Comment by MaDTaZ** [comment]
> Linuxserver historically doesn’t support non “stable” releases, so no.
> 
> If I have some time in the coming days I may create a 10.1 for Jellyfin 10.7.7

well I am on 10.8 now I had not used Jellyfin for a while so just whipped it out and started again but I am getting that the IP address are wrong.

MY docker looks like this

version: '3.7'
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.0-alpha1
    environment:
      PUID: '1000'
      PGID: '1000'
      network_mode: "host"
      TZ: America/Los_Angeles
    ports:
      - 8096
      - '8096:8096'
    volumes:
      - '/media/ExternalHDD/Movie Folder:/mnt/video'
      - '/mnt/user/appdata/jellyfin/config/:/config:rw'
    restart: unless-stopped
    extra_hosts:
      - mf.svc.nhl.com:ip
      - mlb-ws-mf.media.mlb.com:ip
      - playback.svcs.mlb.com:ip
ip is the actual ip took it our because I dont like posting it even thou you see it all over the net lol

**Comment by colino17** [comment]
> Linuxserver historically doesn’t support non “stable” releases, so no.
> 
> If I have some time in the coming days I may create a 10.1 for Jellyfin 10.7.7

This would be appreciated as a stop gap until 10.8 gets a final release. Considering that it just received an alpha release it will likely be a while before the "stable" version of 10.8 is released.

**Comment by crobibero** [comment]
https://github.com/crobibero/Jellyfin.Channels.LazyMan/releases/tag/v10.1

**Comment by PrplHaz4** [comment]
I'm seeing strange behavior (list of channels for a game fails to load) with v10.1 updated from within JF - and the github tags for v10.1 and v11 both seem to point to the same commit (78d6b0259c522de9d2e73c68f0577c96927e9ffa)

When I rollback to v10 and force the hostname/dns I can select a game/channel/quality and it streams great.

**Comment by KX1988** [comment]
> When I rollback to v10 and force the hostname/dns I can select a game/channel/quality and it streams great.
> 
> Is v10.1 working on 10.7.7 for anyone else?

Hi,

I am having the same issue on the latest versions. Everything shows up but no streams to play.

How do you force the hostname/dns on previous version?

**Comment by colino17** [comment]
> > When I rollback to v10 and force the hostname/dns I can select a game/channel/quality and it streams great.
> > Is v10.1 working on 10.7.7 for anyone else?
> 
> Hi,
> 
> I am having the same issue on the latest versions. Everything shows up but no streams to play.
> 
> How do you force the hostname/dns on previous version?

Same issue here. The dates show. The games show. The various channel options show, but the point where there would normally be quality options for each stream is blank.

**Comment by crobibero** [comment]
There is an issue with the ssl certificate for the new domain. This is not an issue with the plugin.

**Comment by PrplHaz4** [comment]
> 
> 
> There is an issue with the ssl certificate for the new domain. This is not an issue with the plugin.

v10.2 looks to be working fine for me now - thank you as always!  It looks like MLBAMGames only uses HTTP so probably the right approach...
