### ISSUE TITLE
Update plugin for 10.4.0 

### ISSUE THREAD

**Issue by crobibero** [crobibero/Jellyfin.Channels.LazyMan#3]

**Comment by lewazo** [comment]
Hey, thanks for this plugin!

Any news on the progress of updating so it works on Jellyfin 10.4.0?

**Comment by crobibero** [comment]
When I was trying to update for 10.4 I couldn’t get any streams to play, hopefully I’ll have more luck with 10.4.1

**Comment by crobibero** [comment]
Updated for 10.4.1
