### ISSUE TITLE
Unable to play games using android

### ISSUE THREAD

**Issue by groenator** [crobibero/Jellyfin.Channels.LazyMan#4]
I installed the latest version of the lazyman plugin. When I am playing a video via android tv or mobile I get a playback error. However, if I use the web client to play a game it works very well.

I am using the latest version of jellyfin server and client.

Any idea why is happening?

Thanks!

**Comment by crobibero** [comment]
If it works on web but not android then it's probably an issue with the android app. Since I'm just feeding the Jellyfin server the url to play, there is nothing I can do to help
