### ISSUE TITLE
NHL and MLB Folder not showing up

### ISSUE THREAD

**Issue by MaDTaZ** [crobibero/Jellyfin.Channels.LazyMan#6]
Hey not sure if you are still working on this but I am not seeing anything in the folder at all
JellyFin Version: 10.6.4
Plugin 9.0

**Comment by crobibero** [comment]
It's working for me and others. 
https://www.reddit.com/r/nhl_games/comments/hzl3jy/emby_jellyfin/gj614er/

If it's still not working for you can you please be more specific.

**Comment by MaDTaZ** [comment]
I figured it out I was using Jellyfin outside of docker then the last time I installed Jellyfin I installed in docker so it was the hosts file that I had not addressed
