### ISSUE TITLE
lazyman won’t show up

### ISSUE THREAD

**Issue by jsampson80** [crobibero/Jellyfin.Channels.LazyMan#8]
I had it working on my pc(win 10) web browser but could not get it to work on my roku Jellyfin app. All the folders just had resolutions but no names and if I clicked one it would jus my automatically just close. 

So I uninstalled Jellyfin and installed  tried Emby, all the folders would show up properly but the wheel just spins on web browser and nothing happens and on my lgtv (webos) it says “no compatible stream found” and my roku stick just crashes and closes right away. 

I went back to Jellyfin and now lazyman won’t show up.

**Comment by crobibero** [comment]
The Emby plugin is no longer under development, so it won't work.
Please provide logs for the plugin not working with Jellyfin. I don't have a Roku to test with, it's possible the Jellyfin Roku app doesn't support playback from channels.
